export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM';
export const LAY_PHIM_DANG_CHIEU = 'LAY_PHIM_DANG_CHIEU';
export const LAY_PHIM_SAP_CHIEU = 'LAY_PHIM_SAP_CHIEU';
export const LAY_CHI_TIET_PHIM_ADMIN = 'LAY_CHI_TIET_PHIM_ADMIN'
