export const LAY_THONG_TIN_NGUOI_DUNG = 'LAY_THONG_TIN_NGUOI_DUNG';
export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG';
export const LAY_THONG_TIN_NGUOI_DUNG_ADMIN = 'LAY_THONG_TIN_NGUOI_DUNG_ADMIN';

